sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - python3.5 -m pip install -e .

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test

notifications:
  slack: idb14:ymFbg1TxzwxeY4ujXkDWOKie