sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install pylint
    - pip install flask

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test

notifications:
  slack: idb14:ymFbg1TxzwxeY4ujXkDWOKie