FORMAT: 1A
HOST: http://polls.apiblueprint.org/

FORMAT: 1A
HOST: http://sample.pandurangpatil.com

# Eklogi API Documentation
Sample api documentation for sample project.

# Allowed HTTPs requests:
<pre>
GET     : Get a resource or list of resources
</pre>

# Possible User Responses:
- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 405 `Method Not Allowed` - requested method is not supported for resource.

# Group Members
Represents the details of politicians.

---
**Member attributes:**

- id `(String)` : Unique identifier. 
- name `(String)` : Name of member.
- facebook `(Link)` : Link to official member's Facebook page.
- twitter `(Link)` : Link to official member's Twitter page.
- website `(Link)` : Link to official website of member.
- date_of_birth `(String)` : Date of Birth.
- party `(String)` : Party which member is part of.
- chamber `(String)` : Which chamber of congress member is part of.
- state `(String)` : State member represents.
- district `(String)` : District member represents (only for house members).

---
## Member Collection [people]
### List all members [GET]
Retrieve all members of current congress.

+ curl "https://api.eklogi.me/people/"

+ Response 200 (application/json)

        [
            {
                "id": "K000388",
                "name": "Trent Kelly",
                "party": "Republican",
                "state": "MS",
                "chamber": "House"
            },
            {
                "id": "Y000064",
                "name": "Tod Young",
                "party": "Republican",
                "state": "IN",
                "chamber": "Senate"
            },
            {
                "id": "C001113",
                "name": "Catherine Cortez Masto",
                "party": "Democrat",
                "state": "NV",
                "chamber": "Senate"
            }
        ...
        ]


## Chamber Collection [people/{chamber}]
### List all members from a chamber [Get]
Returns all members from a chamber, which can be either the house or senate.

+ Parameters
    + chamber (required) ... House or senate

+ curl "https://api.eklogi.me/people/senate/"

+ Response 200 (application/json)

        [
            {
                "id": "C001113",
                "name": "Catherine Cortez Masto",
                "party": "Democrat",
                "state": "NV",
                "chamber": "Senate"
            }
        ...
        ]

+ Response 400 (application/json)

        {
            "error": "no such chamber"
        }

## Single Member [people/{chamber}/{id}.json]
### Retrieve A Single Member [Get]
Return a specific member.

+ Parameters
    + chamber (required) ... House or senate
    + id (required) ... member's Id
    
+ curl "https://api.eklogi.me/senate/C001113.json"

+ Response 200 (application/json)

        {
                "id": "C001113",
                "name": "Catherine Cortez Masto",
                "date_of_birth": "1964-03-29",
                "facebook": "SenatorCortezMasto",
                "twitter": "sencortezmasto",
                "website": "https://www.cortezmasto.senate.gov",
                "party": "Democrat",
                "state": "NV",
                "chamber": "Senate",
                "district": ""
        }

+ curl "https://api.eklogi.me/people/house/K000388.json"

+ Response 200 (application/json)

        {
                "id": "K000388",
                "name": "Trent Kelly",
                "date_of_birth": "1966-03-01",
                "facebook": "reptrentkelly",
                "twitter": "reptrentkelly",
                "website": "https://trentkelly.house.gov",
                "party": "Republican",
                "state": "MS",
                "chamber": "House",
                "district": "1"
        }

# Group Committees
Represents the committees formed in both the senate and the house.

---
**Committee attributes:**
- id `(String)` : Id of committee.
- name `(String)` : Name of committee.
- chair `(String)` : Committee chair.
- chamber `(String)` : Which chamber of congress member is part of.
- num_members `(Integer)` : Number of members on the committee.

---
## Committee Collection [comittees]
### List all committees [GET]
Retrieve all committees of current congress

+ curl "https://api.eklogi.me/comittees/"

+ Response 200 (application/json)

        [
            {
                "id": "HSHA",
                "name": "Committee on Administration",
                "chair": "Gregg Harper",
                "chamber": "House",
                "num_members": 12
            }, 
            
            {
                "id": "HSAG",
                "name": "Committee on Agriculture",
                "chair": "K. Michael Conaway",
                "chamber": "House",
                "num_members": 14
            }
            ...
        ]

## Single Committee [committees/{id}.json]
### Retrieve A Single Commitee [Get]
Return a specific member.

+ Parameters
    + id (required) ... member's Id
    
+ curl "https://api.eklogi.me/committees/HSAG.json"

+ Response 200 (application/json)

        {
            "id": "HSAG",
            "name": "Committee on Agriculture",
            "chair": "K. Michael Conaway",
            "chamber": "House",
            "num_members": 12
        }

+ curl "https://api.eklogi.me/committees/HSHA.json"

+ Response 200 (application/json)

        {
            "id": "HSHA",
            "name": "Committee on Administration",
            "chair": "Gregg Harper",
            "chamber": "House",
            "num_members": 14
        }
        
# Group Bills
Represents the bills introduced in the both the senate and house.

---
**Bill attributes:**
- id `(String)` : Id of bill.
- name `(String)`: Official title for bill
- date `(String)`: Date when bill was introduced
- primare_subject `(String)`: Main subject of the bill
- chamber `(String)`: Chamber where the bill was introduced
- house_passage_date `(String)`: Date the bill passed on House
- senate_passage_date `(String)`: Date the bill passed on Senate

---
## Bill Collection [bills]
### List all bills [GET]
Retrieve all bills introduced during the current congress.

+ curl "https://api.eklogi.me/bills"

+ Response 200 (application/json)

        [
            {
                "id": "hr21-115",
                "name": "Midnight Rules Relief Act of 2017",
                "date": "2017-01-03",
                "primary_subject": "Government Operations and Politics",
                "chamber": "House",
                "house_passage_date": "2017-01-04",
                "senate_passage_date": null
            }, 
            
            {
                "id": "hr210-115",
                "title": "Native American Energy Act",
                "date": "2017-01-03",
                "primary_subject": "Native Americans",
                "chamber": "House",
                "house_passage_date": null,
                "senate_passage_date": null
            }
            ...
        ]

## Single Bill [bills/{id}.json]
### Retrieve A Single Bill [Get]
Return a specific member 
+ Parameters
    + id (required) ... bill's unique Id
    
+ curl "https://api.eklogi.me/bills/hr21-115.json"

+ Response 200 (application/json)

        {
            "id": "hr21-115",
            "name": "Midnight Rules Relief Act of 2017",
            "date": "2017-01-03",
            "primary_subject": "",
            "chamber": "House",
            "house_passage_date": "2017-01-04",
            "senate_passage_date": null
        }

+ curl "https://api.eklogi.me/billsvo/hr210-115.json"

+ Response 200 (application/json)

        {
            "id": "hr210-115",
            "title": "Native American Energy Act",
            "date": "2017-01-03",
            "chamber": "House",
            "house_passage_date": null,
            "senate_passage_date": null
        }
        
# Group Votes
Represents the detailed votes for specific bills introduced in the both the senate and house.

---
**Votes attributes:**
- id `(String)' : Id of bill on this vote.
- session `(String): Session where vote was casted
- chamber `(String): Chamber where the vote was casted
- question `(String): Question surrounding the bill
- result `(String): Result of the vote
- date `(String): Date when this vote happened
- time `(String): Time the vote was casted
---
## Votes Collection [votes]
### List all votes [GET]
Retrieve all votes on every bill introduced during the current congress.

+ curl "https://api.eklogi.me/votes"

+ Response 200 (application/json)

        [
            {
                "id": "hr21-115",
                "session": "1",
                "chamber": "House",
                "question": "On the Motion",
                "result": "Motion Rejected",
                "date": "2017-01-11",
                "time": "22:07:00"
            }, 
            
            {
                "id": "hr210-115",
                "title": "Native American Energy Act",
                "chamber": "House"
                "question": "On the Motion",
                "result": "Motion Rejected",
                "date": "2017-01-11",
                "time": "21:17:00"
            }
            ...
        ]

## Single Votes [votes/{chamber}/{id}.json]
### Retrieve a vote on specific bill [Get]
Return a specific member.

+ Parameters
    + chamber (required) ... chamber in which vote happened
    + id (required) ... bill's unique Id
    
+ curl "https://api.eklogi.me/votes/senate/hr21-115.json"

+ Response 200 (application/json)

        {
            "id": "hr21-115",
            "session": "1",
            "chamber": "House",
            "question": "On the Motion",
            "result": "Motion Rejected",
            "date": "2017-01-11",
            "time": "22:07:00"
        }

+ curl "https://api.eklogi.me/votes/senate/hr210-115.json"

+ Response 200 (application/json)

        {
            "id": "hr210-115",
            "title": "Native American Energy Act",
            "chamber": "House"
            "question": "On the Motion",
            "result": "Motion Rejected",
            "date": "2017-01-11",
            "time": "21:17:00"
        }